#CI项目
name: QCA-ALL

#CI计划
on:
  #自动编译：当Auto-Clean运行完成后
  workflow_run:
    workflows: ["Auto-Clean"]
    types:
      - completed
  #手动编译
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: '手动调整插件包，多个请用\n符号隔开。'
        required: false
        type: string
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: 'false'
        required: false
        type: boolean

#CI权限
permissions: write-all

#CI任务
jobs:
  config:
    name: ${{matrix.CONFIG}}
    strategy:
      fail-fast: false
      #max-parallel: 3
      matrix:
        CONFIG: [build-openwrt-CM520-KKT, build-openwrt-CM520-KYT, build-openwrt-GDOCK-KKT, build-openwrt-GDOCK-KYT]
        SOURCE: [coolsnowwolf/lede]
        BRANCH: [master]

    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      #编译配置
      WRT_CONFIG: build-openwrt-CM520-KKT
      WRT_SH：Scripts/CM520/CM520-KKT.sh
      WRT_CONFIG: build-openwrt-CM520-KYT
      WRT_SH：Scripts/CM520/CM520-KYT.sh
      WRT_CONFIG: build-openwrt-GDOCK-KKT
      WRT_SH：Scripts/GDOCK/GDOCK-KKT.sh
      WRT_CONFIG: build-openwrt-GDOCK-KYT
      WRT_SH：Scripts/CM520/CM520-KYT.sh
      #源码链接
      WRT_REPO: https://github.com/${{matrix.SOURCE}}.git
      #源码分支
      WRT_BRANCH: ${{matrix.BRANCH}}